package View;

import Control.Defunto_Ctrl;
import Model.Defunto;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class JCadastroDefunto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JCadastroDefunto.class.getName());

    public JCadastroDefunto() {
        initComponents();
        
        rtCadInfo.setVisible(false);        
        setLocationRelativeTo(null);
        
        cxIdDefunto.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                rtErroId.setText("");
                cxIdDefunto.setForeground(UIManager.getColor("TextField.foreground"));
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                rtErroId.setText("");
                cxIdDefunto.setForeground(UIManager.getColor("TextField.foreground"));
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
        cxNomeDefunto.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                rtErroNome.setText("");
                cxNomeDefunto.setForeground(UIManager.getColor("TextField.foreground"));
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                rtErroNome.setText("");
                cxNomeDefunto.setForeground(UIManager.getColor("TextField.foreground"));
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        rtNomeDefunto = new javax.swing.JLabel();
        rtCpfDefunto = new javax.swing.JLabel();
        rtDataNascimento = new javax.swing.JLabel();
        rtDataObito = new javax.swing.JLabel();
        rtCemiterio = new javax.swing.JLabel();
        rtCadastroDefunto = new javax.swing.JLabel();
        rtTipoObito = new javax.swing.JLabel();
        rtCadInfo = new javax.swing.JLabel();
        cxNomeDefunto = new javax.swing.JTextField();
        cxIdDefunto = new javax.swing.JTextField();
        cxCemiterio = new javax.swing.JTextField();
        cbTipoObito = new javax.swing.JComboBox<>();
        cbDiaNasc = new javax.swing.JComboBox<>();
        cbMesNasc = new javax.swing.JComboBox<>();
        cbAnoNasc = new javax.swing.JComboBox<>();
        cbDiaObito = new javax.swing.JComboBox<>();
        cbMesObito = new javax.swing.JComboBox<>();
        cbAnoObito = new javax.swing.JComboBox<>();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        rtErroId = new javax.swing.JLabel();
        rtErroNome = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtNomeDefunto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtNomeDefunto.setText("Nome do defunto:");

        rtCpfDefunto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtCpfDefunto.setText("ID:");

        rtDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtDataNascimento.setText("Data de nascimento:");

        rtDataObito.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtDataObito.setText("Data de obito:");

        rtCemiterio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtCemiterio.setText("Cemitério:");

        rtCadastroDefunto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rtCadastroDefunto.setText("Cadastro de defunto");

        rtTipoObito.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rtTipoObito.setText("Tipo de obito:");

        rtCadInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCadInfo.setForeground(new java.awt.Color(255, 0, 0));
        rtCadInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rtCadInfo.setText("Preencha todos os campos");

        cxNomeDefunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeDefuntoActionPerformed(evt);
            }
        });

        cxIdDefunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdDefuntoActionPerformed(evt);
            }
        });

        cbTipoObito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Violenta", "Indeterminado", "Pendente" }));
        cbTipoObito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoObitoActionPerformed(evt);
            }
        });

        cbDiaNasc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbDiaNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMesNasc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbMesNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMesNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesNascActionPerformed(evt);
            }
        });

        cbAnoNasc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbAnoNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        cbDiaObito.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbDiaObito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMesObito.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbMesObito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbAnoObito.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbAnoObito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        rtErroId.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        rtErroNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rtCemiterio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtDataObito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtCpfDefunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtNomeDefunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtTipoObito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtCadInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxCemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoObito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbDiaObito, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDiaNasc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMesNasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMesObito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbAnoNasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbAnoObito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxNomeDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rtErroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxIdDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rtErroId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(rtCadastroDefunto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rtCadastroDefunto)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtNomeDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtCpfDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtDataObito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtCemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtTipoObito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxNomeDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtErroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxIdDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtErroId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAnoObito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMesObito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDiaObito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoObito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastrar)
                            .addComponent(btCancelar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rtCadInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxIdDefuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdDefuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdDefuntoActionPerformed

    private void cbMesNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesNascActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cxNomeDefuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeDefuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeDefuntoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void cbTipoObitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoObitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoObitoActionPerformed
    
    private void cancelar(){
        cxNomeDefunto.setText("");
        cxIdDefunto.setText("");
        cxCemiterio.setText("");
        cbDiaNasc.insertItemAt("Dia", 0);
        cbMesNasc.insertItemAt("Mes", 0);
        cbAnoNasc.insertItemAt("Ano", 0);
        cbDiaObito.insertItemAt("Dia", 0);
        cbMesObito.insertItemAt("Mes", 0);
        cbAnoObito.insertItemAt("Ano", 0);
    }
    
    private void cadastrar(){
        cxNomeDefunto.setText(cxNomeDefunto.getText().replaceAll("\\s+", ""));
        cxIdDefunto.setText(cxIdDefunto.getText().replaceAll("\\s+", ""));
        cxCemiterio.setText(cxCemiterio.getText().replaceAll("\\s+", ""));
                
        LocalDate data_natalidade;
        try{
            data_natalidade = LocalDate.of(
                    Integer.parseInt(cbDiaNasc.getSelectedItem().toString()),
                    Integer.parseInt(cbMesNasc.getSelectedItem().toString()),
                    Integer.parseInt(cbAnoNasc.getSelectedItem().toString())
            );
        }catch(Exception e){
            JOptionPane.showMessageDialog(
                null,
                "Data inválida:\n" + e,
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        LocalDate data_Obito;
        try{
            data_Obito = LocalDate.of(
                    Integer.parseInt((String) cbDiaObito.getSelectedItem()),
                    Integer.parseInt((String) cbMesObito.getSelectedItem()),
                    Integer.parseInt((String) cbAnoObito.getSelectedItem())
            );
        }catch(Exception e){
            JOptionPane.showMessageDialog(
                null,
                "Data inválida:\n" + e,
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Defunto defunto = new Defunto(
                data_Obito,
                (String) cbTipoObito.getSelectedItem(),
                cxCemiterio.getText(),                
                cxNomeDefunto.getText(),
                data_natalidade,
                0
        );
        
        try {
            Defunto_Ctrl.getInstancia().cad_Defunto(defunto);
            JOptionPane.showMessageDialog(
                null,
                "Defunto cadastrado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                null,
                "Erro ao cadastrar defunto:\n" + e,
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
    }
    
    public void rtErroId(){
        rtCadInfo.setVisible(false);
        rtErroId.setText("Este ID já foi cadastrado");
        cxNomeDefunto.setForeground(Color.red);
    }
    
    public void rtErroNome(){
        rtCadInfo.setVisible(false);
        rtErroId.setText("Este nome já foi cadastrado");
        cxNomeDefunto.setForeground(Color.red);
    }
    
    public void msgErro(String msg){
        rtCadInfo.setForeground(Color.red);
        rtCadInfo.setText(msg);
        rtCadInfo.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JCadastroDefunto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbAnoNasc;
    private javax.swing.JComboBox<String> cbAnoObito;
    private javax.swing.JComboBox<String> cbDiaNasc;
    private javax.swing.JComboBox<String> cbDiaObito;
    private javax.swing.JComboBox<String> cbMesNasc;
    private javax.swing.JComboBox<String> cbMesObito;
    private javax.swing.JComboBox<String> cbTipoObito;
    private javax.swing.JTextField cxCemiterio;
    private javax.swing.JTextField cxIdDefunto;
    private javax.swing.JTextField cxNomeDefunto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel rtCadInfo;
    private javax.swing.JLabel rtCadastroDefunto;
    private javax.swing.JLabel rtCemiterio;
    private javax.swing.JLabel rtCpfDefunto;
    private javax.swing.JLabel rtDataNascimento;
    private javax.swing.JLabel rtDataObito;
    private javax.swing.JLabel rtErroId;
    private javax.swing.JLabel rtErroNome;
    private javax.swing.JLabel rtNomeDefunto;
    private javax.swing.JLabel rtTipoObito;
    // End of variables declaration//GEN-END:variables
}
