/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.NavegadorUI;
import Control.Usuario_Ctrl;
import Model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class JRelatorioUsuario extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JRelatorioUsuario.class.getName());
    private NavegadorUI navegador;
    private Usuario usuario;
    
    public JRelatorioUsuario(){
        initComponents();
    }
    
    public JRelatorioUsuario(NavegadorUI navegador, Usuario usuario) {
        this.navegador = navegador;
        this.usuario = usuario;
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        mnBar = new javax.swing.JMenuBar();
        mnItemSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "email", "Telefone", "Admin", "Logradouro", "Numero", "Plano"
            }
        ));
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsers);

        mnItemSair.setText("Voltar");
        mnItemSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnBar.add(mnItemSair);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar_tabela();
    }//GEN-LAST:event_formWindowActivated

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked
        int linha = 0,
            delecao = 0,
            opcao = 0;
        String cpf = "";
        Usuario del = null;
        JTable fonte = (JTable) evt.getSource();
        
        linha = fonte.rowAtPoint(evt.getPoint());
        cpf = (String) fonte.getModel().getValueAt(linha, 2);
        
        opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir usuário selecionado?", 
                    "Exclusão", JOptionPane.YES_NO_OPTION);
        
        if(opcao == JOptionPane.YES_OPTION){
            try{
                if(cpf != usuario.getCpf()){
                    del = Usuario_Ctrl.getInstancia().ler_User(cpf);
                    delecao = Usuario_Ctrl.getInstancia().del_User(del);
                    
                    JOptionPane.showMessageDialog(null, "Deletados " + delecao + "usuarios",
                            "Deleção concluída", JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Impossível deletar usuário atual",
                            "Deleção mal-sucedida", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Erro: " + e.toString(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tbUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    
    private void listar_tabela(){
        int linha = 0;
        DefaultTableModel modelo = (DefaultTableModel) tbUsers.getModel();
        
        tbUsers.setDefaultEditor(Object.class, null);
        
        try{
            for(Usuario u : Usuario_Ctrl.getInstancia().ler_User()){
                modelo.insertRow(linha, new Object[]{
                    u.getNome(), u.getCpf(), u.getEmail(), u.getNumero_Telefone(),
                    (u.isAdmin() ? "Sim" : "Não"), u.getEndereco().getRua(),
                    u.getEndereco().getNumero(), u.getPlano().getId()
                });

                linha++;
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar usuários",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            navegador.fecharJRelatorioUsuario();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JRelatorioUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenu mnItemSair;
    private javax.swing.JTable tbUsers;
    // End of variables declaration//GEN-END:variables
}
